<?php

/**
 *
 * @category   Ebizmarts
 * @package    Ebizmarts_Autoresponder
 * @author     Ebizmarts Team <info@ebizmarts.com>
 * @license    http://opensource.org/licenses/osl-3.0.php
 */
?>

<?php
    $customerEmail = $this->getCustomerEmail();
    $_product = $this->getProduct();
    $formAction = $this->getSubscribeUrl();
?>

<?php if($_product): ?>

    <?php if($this->isLoggedIn() || (!$this->isLoggedIn() && Mage::helper('ebizmarts_autoresponder')->isBacktoStockEnabledForGuest()) ): ?>

    <div class="box-collateral block-autoresponder-backtostock">
        <h2><?php echo $this->__('Back to Stock notification'); ?></h2>
        <p><?php echo $this->__('Subscribe to receive a notification when this product become available!'); ?></p>

        <div class="form-add">
            <form id="backtostock-subscription" action="<?php echo $formAction?>" method="post">
                <div>
                    <ul class="form-list">
                        <li>
                            <label for="subscriber_email"><?php echo $this->__('Enter your email address');?></label>
                            <div class="input-box">
                                <input type="text" value="<?php echo $customerEmail; ?>" class="input-text validate-email required-entry" name="subscriber_email" id="subscriber_email" size="35" />
                            </div>
                        </li>
                    </ul>
                    <button type="submit" class="button" title="<?php echo $this->__('Subscribe'); ?>">
                        <span>
                            <span><?php echo $this->__('Subscribe'); ?></span>
                        </span>
                    </button>
                    <input type="hidden" name="redirect_url" value="<?php echo $_product->getProductUrl(); ?>" />
                    <input type="hidden" name="product_id" value="<?php echo $_product->getId(); ?>" />
                </div>
            </form>
        </div>
    </div>

    <script type="text/javascript">
        //<![CDATA[
        var dataForm = new VarienForm('backtostock-subscription', false);
        //]]>
    </script>

    <?php endif; ?>

<?php endif; ?>
