<?php if(Mage::getStoreConfig(Ebizmarts_AbandonedCart_Model_Config::ACTIVE, $this->_getStoreId()) && Mage::getStoreConfig(Ebizmarts_AbandonedCart_Model_Config::ENABLE_POPUP, $this->_getStoreId())): ?>
    <div id="email" style="text-align:center; display:none">
        <p><span id='email_error_msg' class="email_error" style="display:none">&nbsp;</span></p>
        <div style="clear:both; margin-bottom:10px"><h2 style="color:rgb(36,131,199)"><?php echo $this->_popupHeading(); ?></h2><p><?php echo $this->_popupMessage(); ?></p></div>
        <p><span class="email_label" style="margin-right: 5px">Email:</span><span class="email_input"><input type="text"/></span></p>
        <div style="text-align:left; clear:both; margin-top:10px">
        </div>
    </div>

    <script type="text/javascript">
        <?php if(!Mage::getSingleton('customer/session')->isLoggedIn()): ?>
            if (navigator.cookieEnabled) {
                <?php if(isset($_COOKIE['email'])):
                    $email = str_replace(' ', '+', $_COOKIE['email']);
                    if(isset($_COOKIE['subscribe'])):
                        $subscriber = Mage::getModel('newsletter/subscriber')->loadByEmail($email);
                        if(!$subscriber->getId()):
                            Mage::getModel('newsletter/subscriber')->subscribe($email); ?>
                document.cookie = 'subscribe=; expires=Thu, 01 Jan 1970 00:00:01 GMT';
                location.reload();
                <?php endif; ?>
                <?php endif; ?>
                <?php endif; ?>

                var cookieStored = getEmailCookie();
                if (!cookieStored) {
                    Dialog.confirm($('email').innerHTML, {
                        className: "alphacube",
                        id: "popupDialog",
                        width: <?php Print(json_decode(Mage::getStoreConfig(Ebizmarts_AbandonedCart_Model_Config::POPUP_WIDTH, $this->_getStoreId()))); ?>,
                        zIndex: 200,
                        okLabel: 'Confirm',
                        <?php if(!$this->_canCancel()): ?>closeOnEsc: false,
                        <?php else: ?>cancelLabel: 'Close', <?php endif; ?>
                        onOk: function (win) {
                            var inputField = $$('.email_input input[type=text]').first();
                            var email = inputField.value;
                            if (validateEmail(email)) {
                                var now = new Date();
                                var expire = new Date(now.getTime() + (1 * 365 * 24 * 60) * 60000);//[(1 * 365 * 24 * 60) * 60000] == 1 year  -- (Years * Days * Hours * Minutes) * 60000
                                document.cookie = 'email=' + email + '; expires=' + expire;
                                <?php if($this->_canShowSubscription()): ?>
                                document.cookie = 'subscribe=true; expires=' + expire;
                                location.reload();
                                <?php else: ?>
                                win.close();
                                <?php endif ?>
                            } else {
                                $('email_error_msg').innerHTML = 'Not a valid e-mail address';
                                $('email_error_msg').setStyle({color: '#F00'});
                                $('email_error_msg').show();
                                Windows.focusedWindow.updateHeight();
                                new Effect.Shake(Windows.focusedWindow.getId());
                            }
                        }
                    });

//                    var win = new Window({
//                        className: 'alphacube',
//                        resizable: false,
//                        closable: true,
//                        minimizable: false,
//                        maximizable: false,
//                        draggable: false,
//                        width: 400,
//                        height: 200,
//                        destroyOnClose: true,
//                        okLabel: 'Confirm',
//                        onClose: function () {
//                            alert('hola');
//                        }
//                    });
//                    win.setZIndex(200);
//                    win.setContent('email');
//                    //win.getContent().innerHTML= "<div style='padding:10px'>Duisl ullan ex et am vulputem augiam doloreet amet enibh eui te dipit acillutat acilis amet, suscil er iuscilla con utat, quisis eu feugait ad dolore commy nullam iuscilisl iureril ilisl del ut pratuer iliquis acipissit accum quis nulluptat. Dui bla faccumsan velis auguero con henis duismolor sumsandrem quat vulluptat alit er iniamcore exeriure vero core te dit ut nulla feummolore commod dipis augiamcommod tem ese dolestrud do odo odiamco eetummy nis aliquamcommy nonse eu feugue del eugiamconsed ming estrud magnis exero eumsandio enisim del dio od tat.sumsan et pratum velit ing etue te consequis alis nullan et, quis am iusci bla feummy.</div>"
//                    var size = win.getSize();
//                    win.showCenter();
//
//
//
//                    closePopup = {
//                        onClick: function(eventName, win){
//                            alert('gogo');
//                            if(win == $('overlay_modal')){
//                                win.close();
//                            }
//                        }
//                    };
//                    Windows.addObserver(closePopup);
                }

                <?php if(!$this->_canCancel()): ?>
                $$('.cancel_button').each(function (element) {
                    element.remove();
                });
                <?php else: ?>
//                    $$('.cancel_button').each(function (element) {
//                        element.setZIndex(element.getZIndex()-1);
//                    });
                <?php endif; ?>
            }
        <?php endif; ?>
        function validateEmail(email) {
            var re = /^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
            return re.test(email);
        }

        function getEmailCookie(){
            var cookie = document.cookie;
            var cookieArr = cookie.split(';');
            var cookieStored = false;
            for(var i=0;i<cookieArr.length;i++){
                if(cookieArr[i].indexOf('email=') > -1){
                    cookieStored = true;
                }
            }
            return cookieStored;
        }
    </script>
<?php endif; ?>