<?php
/**
 * @see Ebizmarts_MageMonkey_Block_Adminhtml_System_Config_Fieldset_Hint
 */
?>
<div class="magemonkey-notice">
    <img src="http://ebizmarts.com/extension-logo.php?<?php echo $this->getPxParams(); ?>" />
    <h4>
        <?php echo Mage::helper('monkey')->__('<strong style="color:#EA7601;">MageMonkey v%s by</strong> <a target="_blank" href="http://ebizmarts.com"><strong>ebizmarts</strong></a>', $this->getMageMonkeyVersion())?>
    </h4>
    <h4><a href="http://ebizmarts.com/forums/view/1" target="_blank">Need help? Got feedback? Browse ebizmarts' support forums</a><h4>
</div>