<div style="background:#EAF0EE;border:1px solid #CCCCCC;margin-bottom:10px;padding:11px 0 0 10px;">
    <h4>
        <img src="http://ebizmarts.com/extension-logo.php?<?php echo $this->getPxParams(); ?>" /><br>
        <?php echo Mage::helper('ebizmarts_abandonedcart')->__('<strong style="color:#EA7601;">Ebizmarts Abandoned Cart v%s (Beta)</strong> <br>Need help? Got feedback? <a href="mailto:info@ebizmarts.com?Subject=Support Abandoned Cart">Email us</a>', $this->getVersion())?>
    </h4>
</div>