<?php
/**
 * @see Ebizmarts_SweetMonkey_Block_Adminhtml_System_Config_Fieldset_Hint
 */
?>
<div class="sweetmonkey-notice">
    <img width="244px" height="60px" src="https://ebizmarts-website.s3.amazonaws.com/Logo_Ebizmarts.png"/>
    <h4>
        <?php echo $this->__('<strong style="color:#EA7601;">Sweet Monkey v%s by</strong> <a target="_blank" href="http://ebizmarts.com"><strong>ebizmarts</strong></a>', $this->getSweetMonkeyVersion()) ?>
    </h4>
    <h3><a style="padding-top: 5px;padding-bottom:5px;padding-left: 30px;padding-right: 30px;background-color:#D75F07 ;color:white;font-weight: bold" href="http://www.mailchimp.com/signup?pid=ebizmarts&source=website" target="_blank">Support MageMonkey, Subscribe for a free MailChimp Account!</a> </h3>
</div>