<?php
/**
 * @see Ebizmarts_SweetMonkey_Block_Adminhtml_System_Config_Fieldset_Hint
 */
?>
<div class="sweetmonkey-notice">
    <img src="http://ebizmarts.com/extension-logo.php?<?php echo $this->getPxParams(); ?>"/>
    <h4>
        <?php echo $this->__('<strong style="color:#EA7601;">Sweet Monkey v%s by</strong> <a target="_blank" href="http://ebizmarts.com"><strong>ebizmarts</strong></a>', $this->getSweetMonkeyVersion()) ?>
    </h4>
</div>