<div style="background:#EAF0EE;border:1px solid #CCCCCC;margin-bottom:10px;padding:11px 0 0 10px;">
    <h4>
        <img src="http://ebizmarts.com/extension-logo.php?<?php echo $this->getPxParams(); ?>" /><br>
        <?php echo Mage::helper('ebizmarts_autoresponder')->__('<strong style="color:#EA7601;">Ebizmarts Autoresponder v%s</strong> <br>Need help? Got feedback? <a href="mailto:info@ebizmarts.com?Subject=Support Autoresponder">Email us</a>', $this->getVersion())?>
        <?php if(!Mage::helper('mandrill')->useTransactionalService()): ?>
            <div class="box error-msg" style="padding-left: 30px;">
                You must setup <a class="action-link-holder" href="<?php echo Mage::helper("adminhtml")->getUrl("adminhtml/system_config/edit/section/mandrill"); ?>" >Mandrill</a> extension to use this extension
            </div>
        <?php endif; ?>
    </h4>
</div>