<script type="text/javascript">
    //<![CDATA[
    function check2() {
        new Ajax.Request('<?php echo $this->getAjaxCheckUrl() ?>', {
            method: 'get',
            onSuccess: function (transport) {

                if (transport.responseText == 1) {
                    alert('All remote orders for Ecommerce360 were deleted')
                }
                else {
                    alert('An error happened deleting remote orders in Ecommerce360')
                }
            }
        });
    }
    //]]>
</script>

<?php echo $this->getButtonHtml() ?>