<script type="text/javascript">
    //<![CDATA[
    function check() {
        new Ajax.Request('<?php echo $this->getAjaxCheckUrl() ?>', {
            method:     'get',
            onSuccess: function(transport){

                if (transport.responseText == 1){
                    alert('All local orders for Ecommerce360 was deleted')
                }
                else {
                    alert('En error happens deleting local orders in Ecommerce360')
                }
            }
        });
    }
    //]]>
</script>

<?php echo $this->getButtonHtml() ?>