<?php

$lists       = $this->getLists();
$myLists     = $this->getSubscribedLists();
$generalList = $this->getGeneralList();

?>
<div class="page-title">
    <h1><?php echo $this->__('Newsletter Subscription'); ?></h1>
</div>
<form action="<?php echo $this->getUrl('monkey/customer_account/saveadditional'); ?>" name="mailchimp_additional" id="mailchimp-additional" method="post">
	<div class="fieldset">
		<?php echo $this->getBlockHtml('formkey'); ?>
		<ul class="monkey-additional-lists">

			<!-- General Subscription -->
			<li class="listdata"><?php echo $this->listLabel($generalList); ?>
				<?php if(is_array($generalList['interest_groupings'])): ?>
					<div id="interest_groupings_<?php echo $generalList['id']; ?>" class="interest-groupings">
					<?php foreach($generalList['interest_groupings'] as $group): ?>
						<div class="grouping">
							<strong><?php echo $group['name']; ?></strong>
							<?php echo $this->renderGroup($group, $generalList); ?>
						</div>
					<?php endforeach; ?>
					</div>

				<?php endif; ?>
			</li>
			<!-- General Subscription -->

				<!-- Additional Lists -->
			<?php
				foreach($lists as $list):
					$igroups = $list['interest_groupings'];
			?>

				<li class="listdata"><?php echo $this->listLabel($list); ?>
				<?php if(is_array($igroups)): ?>
					<div id="interest_groupings_<?php echo $list['id']; ?>" class="interest-groupings">
					<?php foreach($igroups as $group): ?>
						<div class="grouping">
							<strong><?php echo $group['name']; ?></strong>
							<?php echo $this->renderGroup($group, $list); ?>
						</div>
					<?php endforeach; ?>
					</div>

				<?php endif; ?>
				</li>

			<?php endforeach; ?>
				<!-- Additional Lists -->

		</ul>
	</div>
	<input type="hidden" name="state" value="" id="form-state" />
    <div class="buttons-set">
        <button type="submit" title="<?php echo $this->__('Save') ?>" class="button"><span><span><?php echo $this->__('Save') ?></span></span></button>
    </div>
</form>
<script type="text/javascript">
	document.observe("dom:loaded", function() {

		removeManageNewsletter();

		//Handle newsletter subscribe/unsubscribe checkbox events
		$$('input.monkey-list-subscriber').each(function(chk){

				if( !chk.checked ){
					var groupings = $('interest_groupings_'+chk.value);
					if(groupings){
						groupings.select('select', 'input').invoke('writeAttribute', 'disabled', 'disabled');
					}
				}

				chk.observe('change', function(){

					var groupings = $('interest_groupings_'+this.value);
					if(groupings){
						var elements = groupings.select('select', 'input');
						if(this.checked){
							elements.invoke('removeAttribute', 'disabled');
						}else{
							elements.invoke('writeAttribute', 'disabled', 'disabled');
						}
					}

				});
		});

		//Load viewstate on hidden field for later process
		$('form-state').writeAttribute('value', $('mailchimp-additional').serialize());

	});
</script>