<div class="mandrill-notice">
    <img src="http://ebizmarts.com/extension-logo.php?<?php echo $this->getPxParams(); ?>" />
    <h4>
        <?php echo $this->__('<strong style="color:#EA7601;">Mandrill v%s by</strong> <a target="_blank" href="http://ebizmarts.com"><strong>ebizmarts</strong></a>', $this->getMandrillVersion())?>
    </h4>
    <h4><?php echo $this->__('Need help? Got feedback? <a href="http://ebizmarts.com/forums/view/1" target="_blank">Browse ebizmarts\' support forums</a>'); ?><h4>
</div>