<div class="mandrill-notice">
    <img src="http://ebizmarts.com/extension-logo.php?<?php echo $this->getPxParams(); ?>" />
    <h4>
        <?php echo $this->__('<strong style="color:#EA7601;">Mandrill v%s by</strong> <a target="_blank" href="http://ebizmarts.com"><strong>ebizmarts</strong></a>', $this->getMandrillVersion())?>
        <br>
        <?php echo $this->__('Need help? See our <a href="http://wiki.ebizmarts.com/installation" target="_blank">Wiki</a> or browse our <a href="http://ebizmarts.com/forums/view/1" target="_blank">support forums</a> Got feedback? <a href="mailto:info@ebizmarts.com?Subject=MageMonkey Version %s">Email us</a>', $this->getMandrillVersion())?>
    </h4>
</div>