<?php
	$lists = $this->getLists();
	$check = $this->checkStatus();
	$generalList   = $this->getGeneralList();
	$auto  = (($check === 1) OR ($check === 3));
?>
<script type="text/javascript">
addSubscribeToPost = function (element){

	if( $('magemonkey-subscribe') ){
		$('magemonkey-subscribe').remove();
	}

	if(element.checked){
        var inputer = new Element('input', { name: "magemonkey_subscribe", id: "magemonkey-subscribe", value: "1", type: "hidden" });
        var listValue = new Element('input', { name: element.readAttribute('name'), id: "subscribe", value: element.getValue(), type: "hidden" });
        try{
            Element.insert(Form.findFirstElement(payment.form), inputer);
            Element.insert(Form.findFirstElement(payment.form), listValue);
        }catch(notelem){
            $("co-payment-form").insert(inputer);
            $("co-payment-form").insert(listValue);
        }
	}

}
addGroupToPost = function (element){
	if(element.checked){
        try{
        	var group = new Element('input', { name: element.readAttribute('name'), id: element.readAttribute('id'), value: element.getValue(), checked:true, type: "checkbox" });
            Element.insert(Form.findFirstElement(payment.form), group);
        }catch(notelem){
            $("co-payment-form").insert(group);
        }
	}
}
addElementToPost = function (element){

	var formInputId = element.readAttribute('id') + '-serialize';

	if($(formInputId)){
	 $(formInputId).remove();
	}

	var inp = new Element('input', { name: element.readAttribute('name'), id: formInputId, value: element.getValue(), type: "hidden" });

	Element.insert( Form.findFirstElement(payment.form), inp);

}
</script>
<div class="buttons-set"<?php if($check === 3): ?> style="display:none;"<?php endif;?>>
<!-- General Subscription -->
<?php echo $this->getBlockHtml('formkey'); ?>
<ul class="monkey-additional-lists">
	<li class="listdata"><?php echo $generalList['name']; ?>
		<input<?php if($auto): ?> checked="checked"<?php endif;?> type="checkbox" onchange="addSubscribeToPost(this);" name="list[<?php echo $generalList['id'] ?>][subscribed]" id="magemonkey-trigger" value="<?php echo $generalList['id']; ?>" title="<?php echo $generalList['name']; ?>" class="monkey-list-subscriber" />
		<?php if(is_array($generalList['interest_groupings'])): ?>
			<div id="interest_groupings_<?php echo $generalList['id']; ?>" class="interest-groupings">
			<?php foreach($generalList['interest_groupings'] as $group): ?>
				<div class="grouping">
					<strong><?php echo $group['name']; ?></strong>
					<?php echo $this->renderGroup($group, $generalList); ?>
				</div>
			<?php endforeach; ?>
			</div>

		<?php endif; ?>
	</li>
</ul>
<!-- General Subscription -->
</div>
<?php
//Check if there's additional list selected, if not Dont show this section
if(count($lists) > 0):
	echo $this->getChildHtml('left.monkeysignup');
endif;
?>

<script type="text/javascript">
//Handle newsletter subscribe/unsubscribe checkbox events
$$('input.monkey-list-subscriber').each(function(chk){

		if( !chk.checked ){
			var groupings = $('interest_groupings_'+chk.value);
			if(groupings){
				groupings.select('select', 'input').invoke('writeAttribute', 'disabled', 'disabled');
			}
		}

		chk.observe('change', function(){

			var groupings = $('interest_groupings_'+this.value);
			if(groupings){
				var elements = groupings.select('select', 'input');
				if(this.checked){
					elements.invoke('removeAttribute', 'disabled');
				}else{
					elements.invoke('writeAttribute', 'disabled', 'disabled');
				}
			}

		});
});

addSubscribeToPost($('magemonkey-trigger'));

if( $$('div#checkout-step-review div.monkey-multisubscribe').length ){

  var event = 'change';

  //Radio||Checkbox
  $$('div#checkout-step-review div.monkey-multisubscribe input').each(function(input){

	  if(input.readAttribute('type') == 'radio'){
		  event = 'click';
	  }

	  input.observe(event, function(){
		  addElementToPost(this);
	  });
  });

  $$('div#checkout-step-review div.monkey-multisubscribe select').each(function(ddl){
	  ddl.observe(event, function(){
		  addElementToPost(this);
	  });
  });

}
//Handle newsletter subscribe/unsubscribe checkbox events
$$('.interest-groupings input').each(function(group){
  group.observe('change', function(){
	 if(group.checked){
	    	addGroupToPost(group);
	 }
  });
});
</script>