<?php $products = $this->getProducts(); ?>
<table cellspacing="0" cellpadding="0" border="0" width="650" style="border:1px solid #EAEAEA;">
    <?php foreach ($products as $product): ?>
        <?php if ($product->getImage() == "no_selection" && $product->getTypeId() == "configurable") {
            $conf = Mage::getModel('catalog/product_type_configurable')->setProduct($product);
            $simple_collection = $conf->getUsedProductCollection()->addAttributeToSelect('*')->addFilterByRequiredOptions();
            foreach ($simple_collection as $simple_product) {
                echo $simple_product->getSku() . " - " . $simple_product->getName() . " - " . Mage::helper('core')->currency($simple_product->getPrice()) . "\n";
                if ($simple_product->getImage() != "no_selection") {
                    $imageUrl = $simple_product->getThumbnailUrl();
                    break;
                }
            }
        } else {
            $imageUrl = $product->getThumbnailUrl();
        }
        ?>
        <tr>
            <td valign="top" align="left" style="padding:3px 9px"><a href="<?php echo $product->getProductUrl(); ?>"
                                                                     alt="<?php echo $this->escapeHtml($product->getName()); ?>"
                                                                     target="_blank"><img src="<?php echo $imageUrl; ?>"
                                                                                          alt="<?php echo $this->escapeHtml($product->getName()); ?>"/></a>
            </td>
            <td valign="top" align="left" style="padding:3px 9px">
                <p><?php echo $this->escapeHtml($product->getName()); ?></p><?php echo $product->getShortDescription(); ?>
            </td>
        </tr>
    <?php endforeach; ?>
</table>